//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnemyCoord
    {
        public int Id { get; set; }
        public Nullable<int> EnemyId { get; set; }
        public Nullable<int> CoordX { get; set; }
        public Nullable<int> CoordY { get; set; }
    
        public virtual Enemy Enemy { get; set; }
    }
}
