//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserItem
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserArmor { get; set; }
        public Nullable<int> UserAttack { get; set; }
        public Nullable<int> UserHP { get; set; }
        public Nullable<int> ItemAttack { get; set; }
        public Nullable<int> ItemDefense { get; set; }
        public Nullable<int> HPregeneration { get; set; }
        public string ItemName { get; set; }
    }
}
