//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Inventories = new HashSet<Inventory>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Level { get; set; }
        public int Class_ID { get; set; }
        public int XP { get; set; }
        public Nullable<int> XP_needed { get; set; }
        public string ASP_ID { get; set; }
        public string Image { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> HP { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventories { get; set; }
    }
}
